apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-node-1
spec:
  rules:
  - host: k8s-node-1
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
