apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hackathon.vm.pl
spec:
  rules:
  - host: hackathon.vm.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: apache
          servicePort: 80
