apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mysql-data1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data1/mysql
